### ISSUE TITLE
PCheckBox: unable to be aware of a programmatically changed value

### ISSUE THREAD

**Issue by st-daristodemo** [PonySDK/PonySDK#83]
It would be nice to either have:
- the method void `setValue(final Boolean value)` to call `onValueChange(..)` so listeners are notified
- or some kind of `click()` method that would allow to simulate a user click (and thus, notify the listeners also)

Because it is currently impossible to programmatically modify the value and be notified of that change elsewhere.

**Comment by Nciaravola** [comment]
you can use fireEvent(ClickEnvent)
